### ISSUE TITLE
Generate FieldLabelOption module helpers

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fulma#113]
Current code: `Field.label [ Field.FieldLabelOption.CustomClass "is-normal" ]`

Should be: `Field.label [ Field.Label.CustomClass "is-normal" ]`

**Comment by evilz** [comment]
Alternate spelling make Api more complex for nothing.
New user will ask them self what is the difference ^^ and then there is none.

My point of view ;p
