### ISSUE TITLE
Overlapping components

### ISSUE THREAD

**Issue by whitetigle** [MangelMaxime/Fulma#115]
Hi, I just put that here for history:
![image](https://user-images.githubusercontent.com/883207/38143195-b353510e-343f-11e8-990e-fd7c6d44dd74.png)

It seems date and notification don't mix well. I didn't check the css but maybe notification is always on top?

**Comment by MangelMaxime** [comment]
Don't seems like notification have a `z-index` value.

If you need you can set a custom style for the the datapicker:
https://github.com/MangelMaxime/Fulma/blob/master/docs/src/FulmaElmish/DatePicker.fs#L28-L32

**Comment by whitetigle** [comment]
I also checked and yes, notification doesn't have any `z-index` set. 
Anyway, thanks for the hint Maxime 👍
