### ISSUE TITLE
Fulma breaks with latest dependencies

### ISSUE THREAD

**Issue by AkosLukacs** [MangelMaxime/Fulma#117]
Full Paket update breaks the build in Divider:
`Fulma\src\Fulma.Extensions\Divider.fs(46,39): error FS0001: This expression was expected to have type    'IHTMLProp'    but here has type    'HTMLAttr' `

My guess is that it might be related to `FABLE_COMPILER` compiler directive, or some SSR magic, because if I comment out the `Data(...)` part in that line, it builds successfully
```fs
| Some label -> classes::(*Data("content", label))::*)opts.Props
```

Run `build.cmd WatchDocs`, so Fable can recompile the changes, I can undo that comment-out (so no changes at all), and watch compiles succesfully, `data-content="OR"` attribute is added to the element, and the text in the divider shows up as expected. Stop the watch + full rebuild fails again :confused:

Paket change summary:
```
Fable.React 1.2.2 -> 3.1
Fable.Elmish.React 1.0 -> 1.0.3
Fable.Core 1.3.7 -> 1.3.12
Fable.Compiler and dotnet-fable 1.3.7 -> 1.3.14
```

Had to change some other things as well (change `member this.render () =` to `override this.render () =`) to get it compile, the latest commit in [my fork](https://github.com/AkosLukacs/Fulma) contains the required changes to build it.

**Comment by MangelMaxime** [comment]
Should be fixed now and I release new version of the libraries too.

**Comment by AkosLukacs** [comment]
It's fixed, thanks!
