### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fulma#12]
- [x] Panel
- [x] Modal
- [x] Nav
- [x] Pagination
- [x] Tabs
- [x] Notification
  - [x] Full rework to follow new architecture
  - [ ] ~Cleaner implementation of the `Program`~

**Comment by evilz** [comment]
- [ ] Dropdown
- [ ] Tabs 
- [ ] Notifications
- [ ] Form controls
- [ ] Layout components

**Comment by MangelMaxime** [comment]
Missing [file](http://bulma.io/documentation/form/file/)

**Comment by MangelMaxime** [comment]
All components should be added now.
