### ISSUE TITLE
Simplify the namespace

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fulma#120]
Since the first version of Fulma, I introduced some sub-namespace like Layout, Elements, etc.

User code looks like:

```
open Fulma
open Fulma.Layouts
open Fulma.Elements
// etc.
```

It occured from my usage that in general I end up opening almost all the namespace.

Would it make sense to simplify this and just have `open Fulma` and directly access the whole Fulma API from it ?

I didn't test this changes, but I think this should be doable.

@evilz @alfonsogarciacaro @whitetigle

**Comment by whitetigle** [comment]
Well, it depends on your views I suppose. 
The only file where I have opened all the Fulma namespace is from a  custom component builder module.
Then I usually have 2-4 Fulma sub-namespaces opened but not much more.

**Comment by alfonsogarciacaro** [comment]
That's usually the case for me too. Hmm, I guess we could use `[<AutoOpen>]` in the subnamespaces, but I'm concerned this may cause some name conflicts.

**Comment by kunjee17** [comment]
I also keep open specific name space. I don't if anyone has faced this difficulties but if two component is having same names then there are conflicts. Specifically for properties of component. So, I have to resolve it using either namespaces or full name to that thing.

**Comment by MangelMaxime** [comment]
I don't think Bulma got a component with the same name and will ever would make no sense to have two element button in the same framework at he same level.

For example, the `label` "component" exist for the `form` and the `field` but because for the field it's access via: `Field.label` there is no conflict.

Same for the extension, an extension should not defined classes with the same name as one component coming from Bulma. And if there is two extension for the same component (it's actually the case for the `steps` I think) then, it's a problem to solve in Fulma.Extension packages.

This is the reason behind #53

Opening 2-4 sub-namespaces is like opening full Fulma API (in the case of 3-4 :) ).

I think we should avoid `[<AutoOpen>]` in API and in reality remapping the namespace paths would have the same effects.

Thanks all for your feedbacks :) I will take the time to digest them.

**Comment by alfonsogarciacaro** [comment]
That makes sense, @MangelMaxime. If there're no possibility of conflict (as @kunjee17 says we have to look especially at DU case names) I agree it's more convenient to open all submodules at once.

I do think `[<AutoOpen>]` can be useful here, because it won't break existing code and it only opens the modules if the parent namespace is open. So:

```fsharp
open Fulma
```

Would have the same effect as (if `Fulma.Layouts` and `Fulma.Elemenst` are decorated with `[<AutoOpen>]`):

```fsharp
open Fulma
open Fulma.Layouts
open Fulma.Elements
```

But there won't be any effect if `open Fulma` statement is missing. So it'd be quite safe in this case.

**Comment by MangelMaxime** [comment]
DU cases names are always prefixed by a module statement so should be fine here.

**Comment by MangelMaxime** [comment]
For references:

```fs
open Fulma.Elements
open Fulma.Elements.Form
open Fulma.Components
open Fulma.Layouts
```

become

```fs
open Fulma
```

------

```fs
open Fulma.Extra.FontAwesome
```

become 

```fs
open Fulma.FontAwesome
```

----

I ported my production app and the docs site without conflict in the Fulma API.

The only, special case is if you have:

```fs
open Fulma
open Elmish
```

then you get warning from Ionide.

And in general you want to write:

```fs
open Elmish
open Fulma
```

This happen if you are using `Fulma.Elmish` package.

**Comment by whitetigle** [comment]
Lol. I was going to finish my work then Paket had this TLS error. 
So I updated Paket and installed all the packages again for my app just in case. 
And so Fulma got updated and now Ionide is screaming! 😉

**Comment by MangelMaxime** [comment]
Hum... @whitetigle if you just do a `paket restore` then you should have the same version as before.

Did you delete your `paket.lock` or `paket update` ?

**Comment by whitetigle** [comment]
Well I just added another lib so without much thinking I ran `paket install` instead. That's whay it happened.
Anyway, I just finished refactoring with the new version and yes it's much much cleaner now without all these dependencies to open. 👍
