### ISSUE TITLE
Datepicker: can't select 2018. september 30

### ISSUE THREAD

**Issue by AkosLukacs** [MangelMaxime/Fulma#123]
The datepicker needs one more row:
(if you go to the next month, sept. 30. is disabled)
![image](https://user-images.githubusercontent.com/844331/38674750-ca60a9d0-3e55-11e8-9e25-89b8af8ef197.png)

**Comment by MangelMaxime** [comment]
Good catch :)

Fixed in 0.1.0-beta-009. You need to wait after nuget.org to do it's job first.

**Comment by MangelMaxime** [comment]
Just if you update to latest version of Fulma.Elmish, you will need to update your code too because there is a change in the namespace used in Fulma.

See #120
