### ISSUE TITLE
Add documentation about NoColor and CustomColor

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fulma#124]
CustomColor allow:

FSharp code:

```fs
let inline isFrontsPoly<'a> = IsCustomColor "poly-fronts"
let inline isInstallationsPoly<'a> = IsCustomColor "poly-installations"

let private viewFilters =
    Field.div [ Field.IsGrouped ]
        [ yield! Checkradio.checkboxInline [ Checkradio.Color isInstallationsPoly
                                             Checkradio.HasBackgroundColor ]
                [ str "Installations" ]
          yield! Checkradio.checkboxInline [ Checkradio.Color isFrontsPoly
                                             Checkradio.HasBackgroundColor ]
                [ str "Fronts" ]
          yield! Checkradio.checkboxInline [ ]
                [ str "Zones fixes" ] ]
```

SCSS code:
```scss
@import "./../../node_modules/bulma/sass/utilities/initial-variables";
@import "./../../node_modules/bulma/sass/utilities/functions";

// Setup custom Colors
$poly-installations: #9930ca;
$poly-installations-invert: findColorInvert($poly-installations);
$poly-fronts: #55b6ee;
$poly-fronts-invert: findColorInvert($poly-fronts);

// Add new color variables to the color map.
@import "./../../node_modules/bulma/sass/utilities/derived-variables";
$addColors: (
  "poly-fronts":($poly-fronts, $poly-fronts-invert),
  "poly-installations": ($poly-installations, $poly-installations-invert),
);
$colors: map-merge($colors, $addColors);
```

Preview:

<img width="478" alt="capture d ecran 2018-04-13 a 17 09 58" src="https://user-images.githubusercontent.com/4760796/38742690-85e48b80-3f3d-11e8-9f87-10b24e9f7eaf.png">

**Comment by selketjah** [comment]
where exactly in the docs do you think this should be added?
A new thing "Properties" with "Color" as an item (like layouts - container) or added here https://mangelmaxime.github.io/Fulma/#fulma/elements/form

**Comment by MangelMaxime** [comment]
I think we could add a new page `Modifiers` between `Versions` and `Layouts`

My idea, is that this is global to all the Fulma components.

If you think this is a good idea, I prepared a branch with the needed modifications
https://github.com/MangelMaxime/Fulma/tree/proposition_modifiers_doc

**Comment by selketjah** [comment]
Is is correct that Checkradio is not a Fulma component, or am I missing something?

**Comment by selketjah** [comment]
is this finished or does something still need to happen for it?
