### ISSUE TITLE
Field and Control are missing is-expanded class

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fulma#126]

**Comment by MangelMaxime** [comment]
Nothing special here, you "just" need to add the new DU case + doc comment and the class to the `module Classes`.

Then fix the compiler warning and should be good.

**Comment by selketjah** [comment]
I'm going to need some help with the field part:

I've been going through the entire doc page of Bulma forms-addons, but I'm not finding any mention of the field having the property "is-expanded"... It also seems has no effect if I add it to a field via my inspector.

what am I missing here? what is the expected behavior?

**Comment by MangelMaxime** [comment]
There is one here:

```html
<div class="field is-horizontal">
  <div class="field-label"></div>
  <div class="field-body">
    <div class="field is-expanded">
      <div class="field has-addons">
        <p class="control">
          <a class="button is-static">
            +44
          </a>
        </p>
        <p class="control is-expanded">
          <input class="input" type="tel" placeholder="Your phone number">
        </p>
      </div>
      <p class="help">Do not enter the first zero</p>
    </div>
  </div>
</div>
```

But it's probably an error in the documentation. Looking at [form.sass](https://github.com/jgthms/bulma/blob/35452d1513cdaa8d2995878f6856ca51a8787129/sass/elements/form.sass) only the control have a `is-expanded` class

**Comment by selketjah** [comment]
adding or removing it also didn't change much. 
explanation is "Use the is-expanded modifier on the element you want to fill up the remaining space (in this case, the input)"

So only add it to the Control?

**Comment by MangelMaxime** [comment]
Yes, only to control please. Perhaps it's a change since 0.6.2
