### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fulma#127]
- Add a link to paket docs
- Explicit the need to include Bulma by linking to Bulma docs

**Comment by fergusmeiklejohn** [comment]
Is Fulma adding Bulma to devDependencies? If so we need to run `yarn add bulma` before adding Fulma or we get `warning "bulma" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".`

**Comment by MangelMaxime** [comment]
Fulma is not touching your pakcage.json

If you have this warning this is because you already included Bulma in your package.json file.

**Comment by MangelMaxime** [comment]
fable-elmish-react is intended to allow user to play with Elmish.

What you are asking is a template dedicated to Fulma: #82

**Comment by MangelMaxime** [comment]
Just for info, we now have a template for Fulma

https://mangelmaxime.github.io/Fulma/#template

**Comment by MangelMaxime** [comment]
Either both home page or both getting started page I think.

Both solution have their problem at least user will be inform he need to check the projects and look at their documentation.

**Comment by selketjah** [comment]
I'll have a look tomorrow and come up with something
