### ISSUE TITLE
Update to Bulma 0.7

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fulma#128]

**Comment by selketjah** [comment]
Anything you need help with for Bulma 0.7?

**Comment by MangelMaxime** [comment]
Nothing special, I just need to take the time to read Bulma changelog and apply the modification to Fulma.

Will probably do it in the next days because we have some holiday coming in France. But if you want to do/start it no problem just mention it in the issue so we don't do the work twice.

**Comment by MangelMaxime** [comment]
I am also trying to update the Fulma documentation to make it more friendly and allow community to share their experience/snippet etc.

**Comment by selketjah** [comment]
If you agree I can tackle all updates involving color in 0.7.0 and 0.7.1
- new shades available
- color and background color separation

**Comment by MangelMaxime** [comment]
Sure, I let you this part :)

**Comment by kunjee17** [comment]
@selketjah if you it is moved to 0.7.1 then please also update the read me.

**Comment by MangelMaxime** [comment]
@kunjee17 We don't support yet all Bulma 0.7 new feature. I am working on it right now, will update the documentation and version infos later.

I need to explain that version XXX of Fulma support only version YYY of Bulma too.

**Comment by kunjee17** [comment]
@MangelMaxime can you point to which new feature? Fulma did make me lazy. I don't check bulma site lately. And now they changed a lot.

**Comment by MangelMaxime** [comment]
The new features from Fulma perspective are the one added by @selketjah and :

```md
- Add new aspect ratio support for `Image` (since Bulma 0.7.0) 
- Add `is-expanded` to `Button` (since Bulma 0.7.0) 
```

I am also fixing the a missing size screen for the Columns `fullhd`. And adding all the modifier support:

- text alignment
- display: flex, block, etc.
- generic helpers:
  - `"is-clearfix"`
  - `"is-pulled-left"`
  - `"is-pulled-right"`
  - `"is-marginless"`
  - `"is-paddingless"`
  - `"is-overlay"`
  - `"is-clipped"`
  - `"is-radiusless"`
  - `"is-shadowless"`
  - `"is-unselectable"`
  - `"is-invisible"`

There is new features in how Bulma works internally: https://github.com/jgthms/bulma/blob/master/CHANGELOG.md

**Comment by selketjah** [comment]
need help with doing any of these?
We can divide and conquer this (the world eventually)

**Comment by MangelMaxime** [comment]
Splitting the job for the remaining `Modifiers` is really hard because I designing the API on the fly.

They are simple case like the rest of the code:

Here is a quick overview of what I have so far.

```fs
    let parseModifiers options =
        let parseOption result opt =
            match opt with
            | BackgroundColor color -> { result with BackgroundColor = color |> ofBackground |> Some }
            | TextColor color -> { result with TextColor = color |> ofText |> Some }
            | TextWeight textWeight -> { result with TextWeight = textWeight |> TextWeight.ofOption |> Some }
            | Display (screen, display) ->
                let cls = Display.toDisplayClass screen display
                { result with Display = result.Display + " " + cls }
            | DisplayOnly (screen, display) ->
                let cls = Display.toDisplayOnlyClass screen display
                { result with DisplayOnly = result.DisplayOnly + " " + cls }
            | IsClearfix -> { result with IsClearfix = Classes.Helpers.IsClearfix |> Some }
            | IsPulledLeft -> { result with IsPulledLeft = Classes.Helpers.IsPulledLeft |> Some }
            | IsPulledRight -> { result with IsPulledRight = Classes.Helpers.IsPulledRight |> Some }
            | IsMarginless -> { result with IsMarginless = Classes.Helpers.IsMarginless |> Some }
            | IsPaddingless -> { result with IsPaddingless = Classes.Helpers.IsPaddingless |> Some }
            | IsOverlay -> { result with IsOverlay = Classes.Helpers.IsOverlay |> Some }
            | IsClipped -> { result with IsClipped = Classes.Helpers.IsClipped |> Some }
            | IsRadiusless -> { result with IsRadiusless = Classes.Helpers.IsRadiusless |> Some }
            | IsShadowless -> { result with IsShadowless = Classes.Helpers.IsShadowless |> Some }
            | IsUnselectable -> { result with IsUnselectable = Classes.Helpers.IsUnselectable |> Some }
            | IsInvisible (screen, true) -> { result with IsInvisible = result.IsInvisible + " " + ofInvisible screen }
            | IsInvisible (_, false) -> result
            | IsHidden (screen, true) -> { result with IsHidden = result.IsHidden + " " + ofHidden screen }
            | IsHidden (_, false) -> result
            | IsInvisibleOnly (screen, true) -> { result with IsInvisibleOnly = result.IsInvisibleOnly + " " + ofInvisible screen }
            | IsInvisibleOnly (_, false) -> result
            | IsHiddenOnly (screen, true) -> { result with IsHiddenOnly = result.IsHiddenOnly + " " + ofHidden screen }
            | IsHiddenOnly (_, false) -> result
```

I will probably create a PR and ping you in it if you are okay. So you can review the changes or at least give opinion on the `Modifier` API from user point of view.

**Comment by MangelMaxime** [comment]
And yes added "strongly typed DSL" over something not typed at all is challenging and we can't always take the direct path...
