### ISSUE TITLE
Fulma Minimal Template - OSX - fake.sh doesn't have execute rights

### ISSUE THREAD

**Issue by fergusmeiklejohn** [MangelMaxime/Fulma#133]
Running: `./fake.sh build -t Watch` on OSX returns the error: `./fake.sh: Permission denied`

This is because the fake.sh permissions don't include execute

To make it work I fixed the permissions for that file on my mac by running: `chmod 755 fake.sh`

Need to change permissions on the template.

**Comment by MangelMaxime** [comment]
I saw it, my problem is when I create the template the file have the correct permission set.

But when installing from the template, the permission are reset to 744 something...

**Comment by MangelMaxime** [comment]
This is fixed in latest version of the tempalte 1.0.3
