### ISSUE TITLE
Add a note about Ionide usage

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fulma#134]
When user use Ionide we should say to add:

```fs
"FSharp.resolveNamespaces": false,
"FSharp.externalAutocomplete": false,
```

to have a better experience with Fulma.

**Comment by kunjee17** [comment]
Why this is required? Is there any issue raised...

**Comment by MangelMaxime** [comment]
Some people had a hard time due to bad intellisense experience.

For example, in general you write: `Button.Color IsDanger` because Fulma open for you the `Color` module.

However, if you want to write: `Button.Color Color.XXXX`, Ionide will provide intellisense for
`Color.Khaki` if you have `open System` in your code.

Also, those feature of Ionide are mark as experimental but enable ny default... and they slow down Ionide like crazy from my experience. Or having Fulma with a slow intellisense/compilation check is degrading a bit the user experience.

We will just add it has a recommendation, the goal here is just to inform the user.
