### ISSUE TITLE
Minimal Fulma template ships with broken version of paket bootstrapper

### ISSUE THREAD

**Issue by mtnrbq** [MangelMaxime/Fulma#146]
The paket bootstrapper included in the FulmaMininimalTemplate is v5.92.0.0 which suffers from the issue documented in fsprojects/Paket#3065. (tries to use old cypher that has been obsoleted)

I'm preparing a PR to update the bootstrapper to v5.165

**Comment by MangelMaxime** [comment]
Should be fixed in version 1.0.6
