### ISSUE TITLE
DOCS: update introduction pages

### ISSUE THREAD

**Issue by selketjah** [MangelMaxime/Fulma#149]
I got some feedback from developers trying to find out what Fulma is:

_"even after searching it, it took me a while to find what fulma is, even on their own page a small intro that says what bulma is."_

@MangelMaxime if you agree with this, I will:
- update https://mangelmaxime.github.io/Fulma/#home to add a description of Fulma and Bulma with the correct links.
- update https://mangelmaxime.github.io/Fulma/#fulma with a "tell me in one sentence what Fulma is and why it is awesome"

**Comment by MangelMaxime** [comment]
Hey my links are correct on *https://mangelmaxime.github.io/Fulma/#home*

But yes sure, you can send a PR and we can discuss the change their :)

**Comment by selketjah** [comment]
Bad explanation on my side, I am not talking about incorrect links ;)

I will send a PR, showing you will be much easier :p

**Comment by MangelMaxime** [comment]
> Bad explanation on my side, I am not talking about incorrect links ;)

I was just trolling ^^
