### ISSUE TITLE
Fulma FontAwesome: updating to 5.x.x

### ISSUE THREAD

**Issue by selketjah** [MangelMaxime/Fulma#151]
Supported Font Awesome version is currently 4.7.0.
Are there any plans to update Fulma to work with FontAwesome 5?

**Comment by MangelMaxime** [comment]
I think @whitetigle started a work on it but not sure if he had the time to finish it.

When I ported 4.7.0 I created this script: https://github.com/MangelMaxime/Fulma/blob/master/utils/extract-font-awesome.js

It probably need to be adapted to their new website version.
