### ISSUE TITLE
Fulma template: Fable PowerPack not found

### ISSUE THREAD

**Issue by selketjah** [MangelMaxime/Fulma#162]
I get this error when running "paket update" with a freshly installed Fulma Minimal template

> Paket failed with
> -> Package Fable.PowerPack was referenced in /path/to/project/project.fsproj, but it was not found in the paket.lock file in group Main.

I think `nuget Fable.PowerPack` is missing from the `paket.dependencies` file in the template.

**Comment by MangelMaxime** [comment]
Actually, it should be removed from `paket.references` because the templates doesn't need it.
