### ISSUE TITLE
Calendar layout

### ISSUE THREAD

**Issue by bohdanszymanik** [MangelMaxime/Fulma#167]
Something a bit odd with that calendar... I've tried building on two machines and I'm getting the same result.
![calendar](https://user-images.githubusercontent.com/271575/47982462-a655f400-e134-11e8-9e80-b59c6c96b0a1.png)

**Comment by romanstetsenko** [comment]
Yeah, it's a little bit frustrating.
@bohdanszymanik If you don't want to deal with sass you can use the following link : `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-calendar@4.0.2/dist/css/bulma-calendar.min.css">`

**Comment by bohdanszymanik** [comment]
Thx guys, I'll try it out when I get to work. Cheers

**Comment by bohdanszymanik** [comment]
4.0.2 works a treat - thanks all - but how come package.json contains "bulma-calendar": "^5.0.1"? Why not pin it to exactly 4.0.2?

**Comment by MangelMaxime** [comment]
You can pin it to `4.0.2` just that by default npm install the latest version.

**Comment by bohdanszymanik** [comment]
I'll do that in my code - but without doing it in this repo then the calendar won't display properly on a build - seems wrong. Anyhow, happy with answer - I'll close. Thanks,

**Comment by MangelMaxime** [comment]
Ah I probably forget to revert the version change
