### ISSUE TITLE
Fulma Input.Text fails during SSR

### ISSUE THREAD

**Issue by AnthonySuper** [MangelMaxime/Fulma#169]
When I try to render a `Input.text` element on the server, I get the following error:

```
System.MissingMethodException: Method not found: 'HTMLAttr HTMLAttr.NewDefaultValue(System.String)'.
   at Fulma.Input.input@161.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Fulma.Input.input(FSharpList`1 options)
    -- Rest of the code omitted 
```

This has been a bit confusing to me because (as far as I can tell) that bit of code in the repo never tries to call a `NewDefaultValue` method at all.

Any idea what this might be?

**Comment by AnthonySuper** [comment]
```fs
let toValue (c: Fable.Import.React.FormEvent) = c.Value

let withLabel label body =
    Field.div []
        [ Label.label [] [str label]
          body ]

let labledText label value change =
    withLabel label
        (Input.text
            [ Input.OnChange (change << toValue)
              Input.Value value
              Input.Props
                [Props.Required true]])
```

Here's the minimal example.

**Comment by zaaack** [comment]
@AnthonySuper I cannot find `HTMLAttr.NewDefaultValue` in any repo, can you create a minimal reproducible repo?

**Comment by AnthonySuper** [comment]
[Here](https://github.com/AnthonySuper/minimal-fulma-bug-example) is a minimal example repository. The README explains how to use it. 

From the fact that the bug only occurs under certain routing conditions, I think this situation may be more complicated than the stack trace is letting on, unfortunately... Still, hopefully this repository can provide insight.

**Comment by zaaack** [comment]
@AnthonySuper Thanks for your repo.

The `ilspycmd` shows that dotnet compiles `HTMLAttr.DefaultValue` to `HTMLAttr.NewDefaultValue`, I'm afraid this is related to dotnet core version mismatch problem, I tried change `TargetFramework` in `Server.fsproj` to `netcoreapp2.0` as the same as `Fulma` and `Fable.React`, but have no luck. Perhaps you can try with a lower version of dotnet cli, like 2.0. Or send an issue to projects like visualfsharp/dotnetcore, perhaps people there who are more familiar with dotnet core can give some more useful advice. 

```cs
case 4:
    if (opts.Id_0040 != null)
    {
        pc = 5;
        current = HTMLAttr.NewId(opts.Id_0040.get_Value());
        return 1;
    }
    goto case 5;
case 5:
    if (opts.Value_0040 != null)
    {
        pc = 6;
        current = HTMLAttr.NewValue(opts.Value_0040.get_Value());
        return 1;
    }
    goto case 6;
case 6:
    if (opts.DefaultValue_0040 != null)
    {
        pc = 7;
        current = HTMLAttr.NewDefaultValue(opts.DefaultValue_0040.get_Value());
        return 1;
    }
    goto case 7;

```
[Input.cs.zip](https://github.com/MangelMaxime/Fulma/files/2570313/Input.cs.zip)

**Comment by MangelMaxime** [comment]
I will close this issue as there isn't much we can do from this repo.

Feel free to re-open if needed.
