### ISSUE TITLE
Fulma 2.0.0: FontAwesome support.

### ISSUE THREAD

**Issue by whitetigle** [MangelMaxime/Fulma#175]
Hi! 
Just updated my project to new version but I can't get access to Fa.Solid.Book like in the blog sample.
![image](https://user-images.githubusercontent.com/883207/49568101-3784da00-f930-11e8-92aa-636b28f61e82.png)

[Edit]:

```
Fable.FontAwesome (1.0)
      Fable.Core (>= 2.0.2) - restriction: >= netstandard2.0
      Fable.React (>= 4.1.3) - restriction: >= netstandard2.0
```

**Comment by xdaDaveShaw** [comment]
Have you also added `Fable.FontAwesome.Free` (or `.Pro`) to you project's references?

**Comment by whitetigle** [comment]
Sorry for the trouble. I missed the `Important!` section in the doc. 
Thanks for your help!

**Comment by xdaDaveShaw** [comment]
Also, don't forget to update the CSS used to FA5 in your "index.html" ;)

Maybe a PR to the docs is needed to make it a bit more step-by-step.

**Comment by MangelMaxime** [comment]
@xdaDaveShaw 

I was thinking that it should be enough by saying:

> Fable.FontAwesome supports **Font Awesome 5**, while Fulma.FontAwesome was supporting **4.7.0**.

Also not everyone use style link in CSS.

For example, I don't and I am using npm and the `sass` version. 
But others, could use the `less` version etc. 

We updated the documentation to ask people to go to [https://mangelmaxime.github.io/Fulma/#fable-fontawesome](https://mangelmaxime.github.io/Fulma/#fable-fontawesome) so hopefully they will will see the last line :).
