### ISSUE TITLE
Manage `id` for label in form

### ISSUE THREAD

**Issue by evilz** [MangelMaxime/Fulma#29]
We need a way to set an `id` in input field that will be used in `HtmlFor` inside a label.

```fs
div [ ClassName "field" ]
   [ input [ Type "text"; Id "SOME-ID" ]
     label [ HtmlFor "SOME-ID" ] [ str "this is the label"]
   ]
```

Id can be ;
- setted in props
- generated

`id: string option`   ?

**Comment by MangelMaxime** [comment]
I think we can't generate it as there is a lot of possibilities for input combination.

- With icons
- With left icons
- With right icons
- etc.

But yes, I will definitely add an helper to set it easily on the label and any form elements supporting "selection via Label"

**Comment by evilz** [comment]
I still think that both are possible. 
Actually I use a generated Guid as id for my checkbox. 
But I'm pretty sure sometime we will need a custom id.
