### ISSUE TITLE
Show an example of Navbar.burger implementation

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fulma#46]
Would be nice if have an example of how to use Navbar.burger with Fulma.

For example, the official documentation show one here: http://bulma.io/documentation/components/navbar/

**Comment by alfonsogarciacaro** [comment]
FableConf site uses the navbar burger with Elmish state:
https://github.com/fable-compiler/fableconf/blob/44462515b099152fc0a2625f09ddb8a05a2ac3a9/src/Navbar/View.fs#L36-L58

Fable site uses the navbar burger with a static site:
https://github.com/fable-compiler/fable-compiler.github.io/blob/08c6e99dc267f2ad78c1ca7a1b334d60d2ada825/src/components/Navbar.fs#L33-L42

The JavaScript to open/close the menu is in the template:
https://github.com/fable-compiler/fable-compiler.github.io/blob/08c6e99dc267f2ad78c1ca7a1b334d60d2ada825/files/template.hbs#L22-L35

Both cases use the class names directly, but it shouldn't be difficult to change this to Fulma.

**Comment by sandeepc24** [comment]
The issue with Fable-Suave template is that Menu.fs is rendered after DOMContentLoaded is called and hence the click event listener is not hooked up.

**Comment by MangelMaxime** [comment]
@sandeepc24 According to FableConf code there is no need to use DOMContentLoaded. You can manage the state directly in your Model.

**Comment by sandeepc24** [comment]
Not sure how, could you please give an example.

**Comment by sandeepc24** [comment]
I am trying the following code in Menu.fs

`    div [] [
        nav [ClassName "navbar"] [
            div [ClassName "navbar-brand"] [
                div [ClassName "navbar-item"] [ str "Hi"]
                div [ClassName "navbar-burger"; !!("data-target", "navMenu")] [
                    span [] []
                    span [] []
                    span [] []
                ]
            ]

            div [Id "navMenu"; ClassName "navbar-menu"] [
                div [ClassName "navbar-start"] [
                    a [ClassName "navbar-item is-active"; Href (toHash Page.Home) ] [str "Home" ]
                    a [ClassName "navbar-item is-active"; Href (toHash Page.Home) ] [str "Home" ]
                    a [ClassName "navbar-item is-active"; Href (toHash Page.Home) ] [str "Home" ]
                    a [ClassName "navbar-item is-active"; Href (toHash Page.Home) ] [str "Home" ]
                ]
                div [ClassName "navbar-end"] [
                    a [ClassName "navbar-item"; Href (toHash Page.Home) ] [str "Logout" ]
                ]
            ]

        ]
    ]
`

and  I have changed index.html as 
`<!doctype html>
<html>
<head>
		<meta http-equiv="Content-Type" content="text/html" charset="utf-8">
		<title>Fable-Suave Scaffold sample</title>
		
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.5.2/css/bulma.min.css">
		<link rel="stylesheet" href="css/site.css">

		
		<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.0/react.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.4.0/react-dom.min.js"></script>	
	</head>
<body class="app-container">
    <script src="js/shim.min.js"></script>
    <script src="js/fetch.js"></script>
    <div id="elmish-app" class="elmish-app" />
    <script src="./public/bundle.js"></script>
	<script>
			document.addEventListener('DOMContentLoaded', function () {
	
				// Get all "navbar-burger" elements
				var $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
	
				// Check if there are any navbar burgers
				if ($navbarBurgers.length > 0) {
	
					// Add a click event on each of them
					$navbarBurgers.forEach(function ($el) {
						$el.addEventListener('click', function () {
	
							// Get the target from the "data-target" attribute
							var target = $el.dataset.target;
							var $target = document.getElementById(target);
	
							// Toggle the class on both the "navbar-burger" and the "navbar-menu"
							$el.classList.toggle('is-active');
							$target.classList.toggle('is-active');
	
						});
					});
				}
	
			});
		</script>
</body>
</html>
`

**Comment by MangelMaxime** [comment]
You have all the code in the repo..

Here is how you manage the state: https://github.com/fable-compiler/fableconf/blob/44462515b099152fc0a2625f09ddb8a05a2ac3a9/src/Navbar/State.fs

And here you have the code which handle the view: https://github.com/fable-compiler/fableconf/blob/44462515b099152fc0a2625f09ddb8a05a2ac3a9/src/Navbar/View.fs#L36-L58

And register a click to toggle the menu state.

You probably also need to make your application adaptive/responsive: https://github.com/fable-compiler/fableconf/blob/44462515b099152fc0a2625f09ddb8a05a2ac3a9/public/index.html#L6


You **don't need** the `DOMContentLoaded` callback when using Elmish. 

Don't hesitate to clone the repo and play with it.

**Comment by rmunn** [comment]
I think it would also be useful to have an example of how to use dropdowns, or any other UI element that does **not** need separate Javascript (i.e., the example should show one way to handle it all within Fable, swapping out the `is-open` CSS class based on some value in the model).

**Comment by MangelMaxime** [comment]
@rmunn you would want an exemple without the `is-hoverable` class if I understand well. 

Will work on it after fableconf probably.

**Comment by alfonsogarciacaro** [comment]
@rmunn The dropdowns are managed just with CSS, you only JS for the burger button. A simple example using Fable.React (if you're not generating static pages) could be:

``fsharp
let navbarView (model: Model) dispatch =
  nav [ClassName "navbar"] [
    div [ClassName "navbar-brand"] [
      div [ClassName "navbar-item title is-4"] [(* NavBar Brand *)]
      div [
        ClassName "navbar-burger"
        OnClick (fun _ -> dispatch ToggleBurger)
      ] [span [] []; span [] []; span [] []]
    ]
    div [classList ["navbar-menu", true; "is-active", model.isBurgerOpen]] [
      div [ClassName "navbar-start"] [(* NavBar Menu Items *)]
      div [ClassName "navbar-end"] [(* NavBar Buttons *)]
    ]
  ]
```

Of course that would depend on your model, dispatch messages, etc. I just took this from FableConf site, so you would have to change to use Fulma API, sorry!

**Comment by rmunn** [comment]
@alfonsogarciacaro - That's precisely the kind of example I'm talking about. We're going to see more F#/Fable newbies thinking that they have to manage their dropdowns with Javascript, because that's what the Bulma documentation says. What I want to see (but don't have the time to work on myself at the moment) is some Fulma documentation that says "The Fulma way to manage these dropdowns is to make the CSS class show up based on some value in your model, like `model.isBurgerOpen` in this example. Then the button should dispatch a message that toggles that value in the model."

Better yet: the example calls a function (passing it the model) to determine whether the dropdown should be open or closed. The example could have a very simple function `let isBurgerMenuOpen model = model.isBurgerOpen`, but with a comment saying "This example just uses a boolean on the model to decide whether the dropdown is active, but in theory you could do complex calculations here". Then maybe another example would have an input box where you type numbers, and one dropdown opens only if the number is prime, another opens only if the number is divisible by 2, and so on. That's a contrived example, but it's intended to get the idea into newbies' heads that you can tie your dropdown to *any* logic, you just need a consistent function signature `Model -> bool`.

Wish I could afford the time to work on this, in addition to my dozens of other personal projects just waiting for me to get to them, but I'm afraid my contribution at the moment will have to be limited to "Hey, here's an idea".

**Comment by MangelMaxime** [comment]
@rmunn Giving ideas is already helping a lot.

I was planning to add more interactive example, for Fulma in the future exactly to help people understand how it's works and how "to think Fulma + Elmish".

If you have others ideas like that you can open issues to track them :)

**Comment by evilz** [comment]
From what I understand, this subject is more  ELMISH stuff than fulma.
But it is true that in docs we don't put a lot about model and update function.

**Comment by MangelMaxime** [comment]
@evilz Yes it's related to Elmish too.

After, from what I saw by helping people. People using Fulma and asking question on how to do that or that also start using Elmish too. There is two reasons for this:

1. Fulma is the only "CSS wrapper" for Elmish ATM
2 We (I :) ) I often say to people using Bootstrap and others framework like that. That we have Bulma wrapper and it's easier to use because it's full CSS no external JS is needed.

I believe adding some documentation on how to interact with Fulma is a good things. And could help adoption and also allow us to redirect people to the right documentation instead of saying the same thing each time :D

**Comment by rmunn** [comment]
@MangelMaxime -

> If you have others ideas like that you can open issues to track them :)

Just created #48 with an idea for a decent-sized demo that could show off multiple parts of Fulma (and Elmish) working together. A demo is decent-sized, in my opinion, if it's large enough to look like part of a real site (not just a single component), but small enough that the entire code can be read and understood in one sitting.

**Comment by MangelMaxime** [comment]
@rmunn Thanks you for taking the time or making an issue about it. I will work on it for sure after FableConf

**Comment by MangelMaxime** [comment]
Hello, @sandeepc24 you can find a full example of a responsive navbar [here](https://github.com/MangelMaxime/fulma-demo/blob/master/src/App.fs#L16-L65)

**Comment by sandeepc24** [comment]
Thanks.
