### ISSUE TITLE
Add documentation for Layout

### ISSUE THREAD

**Issue by rommsen** [MangelMaxime/Fulma#49]
The documentation does not contain a section about the Layout part of Bulma/Fulma (i.e. Columns etc.). Would be awesome if this could be added.

**Comment by MangelMaxime** [comment]
Should be available in the day :)

**Comment by MangelMaxime** [comment]
@rommsen I just updated the docs site has you can see it's speak now about `Fulma` and not `Fable.Elmish.Bulma` so not everything documented on the docs site is available if you use `Fable.Elmish.Bulma`.

I will publish later in the week an explanation and a migration guide. So no worries :)
