### ISSUE TITLE
Datepicker stopped working in docs

### ISSUE THREAD

**Issue by kunjee17** [MangelMaxime/Fulma#51]
Datepicker sample seems to be stops working in docs.

**Comment by MangelMaxime** [comment]
Ah yes, I know what's the problem. I will fix it in the today thanks you :heart:

**Comment by kunjee17** [comment]
@MangelMaxime it was working yesterday. And thanks.

PS. If you don't mind me asking what is there planned for Fulma.Elmish. Means general direction? or todo list. May be I can help or at least give a try.

**Comment by zaaack** [comment]
In my chrome browser, all buttons in docs stop working, except navigation...

**Comment by MangelMaxime** [comment]
@zaaack Sorry about that it's the same source of problems as for the DatePicker.
I tried to fix another bug into the docs site and it seems like I introduce another bug. 

@kunjee17 Yes I have some ideas for it. I need to create issues to track them.

**Comment by MangelMaxime** [comment]
@kunjee17 @zaaack The docs site has been updated with some bug fixes:

- Remove lazyView to fix [date picker](https://mangelmaxime.github.io/Fulma/#fulma-elmish/date-picker) demo and allow to expands the "code blocks"
- Fix blank rendering of the static content when we click on a the header of a "toggable menu"
