### ISSUE TITLE
Icons size demo display broken

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fulma#52]
Seems like something has been broken on the [icon](https://mangelmaxime.github.io/Fulma/#fulma/elements/icon) page.

The display for the sizes icons is incorrect.

It's seems like we now need to add the Font Awesome size helpers too. 
It's what is done on [Bulma docs now](http://bulma.io/documentation/elements/icon/)

Code taken from Font Awesome website:
```html
<i class="fa fa-camera-retro fa-lg"></i> fa-lg
<i class="fa fa-camera-retro fa-2x"></i> fa-2x
<i class="fa fa-camera-retro fa-3x"></i> fa-3x
<i class="fa fa-camera-retro fa-4x"></i> fa-4x
<i class="fa fa-camera-retro fa-5x"></i> fa-5x
```

I don't know why it's was working before. Perhaps something to do with preact switch but would be a strange behaviour as it have nothing to do with the CSS...

**Comment by MangelMaxime** [comment]
Perhaps this can be an opportunity to implement wrapper for [Font Awesome helpers](http://fontawesome.io/examples/) class like `fa-spin`, `fa-2x`. Or at least a record to get intellisense and not use strings :)

If someone want to give it a try I can give some guidance.

**Comment by EdouardM** [comment]
Hi Maxime 

I'd like to help on this issue! 
Édouard

**Comment by MangelMaxime** [comment]
@EdouardM 

I would do something like that:

In the [FontAwesome.fs file](https://github.com/MangelMaxime/Fulma/blob/master/src/Fulma/Extra/FontAwesome.fs#L816)

```fs
// FontAwesome.fs

// Create a Classes modules like we do for Fulma.Extensions which map the Font Awesome classes values.
module Classes =
    // Example for the Sizes
    module Sizes =
        let [<Literal>] FaLarge = "fa-lg"
        let [<Literal>] Fa3x = "fa-2x"
        let [<Literal>] Fa2x = "fa-3x"

// Create the Types module which serve as an internal DSL
module Types =

    type ISize =
      | FaLarge
      | Fa2x
      | Fa3x

    let ofSize =
        function
        | FaLarge -> Classes.Sizes.FaLarge
        | Fa2x -> Classes.Sizes.Fa2x
        | Fa3x -> Classes.Sizes.Fa3x
        
    type Options =
       { Icon : string option
         Size : string option }

       static member Empty =
         { Icon = None
           Size = None }

    type Option =
      | Icon of IFontAwesomeIcon
      | Size of ISize

let inline faIcon (options: Fulma.Elements.Icon.Types.Option list) (faOptions : Option list) =
    let parseOptions (result : Options) option =
        match option with
        | Size size -> { result with Size = ofSize size |> Some }
        | Icon faIcon -> { result with Icon = unbox<string> faIcon |> Some } // For F# compiler to consider the faIcon as a string

    let opts = options |> List.fold parseOptions Options.Empty

    icon options
        [ i [ classBaseList "fa" [ opts.Icon.Value, opts.Icon.IsSome 
                              opts.Size.Value, opts.Size.IsSome ] ] [ ] ]

// Usage sample would be
Icon.faIcon [ Icon.isLarge ]
    [ Fa.Icon Fa.Slideshare
      Fa.faLarge ]
```

The code I gave you has not been tested it's "pseudo-code" to give you the general direction. But I think the *Usage sample" is the target we are aiming for this feature.

@evilz  Do you agree with my usage proposition ?

**Comment by MangelMaxime** [comment]
The code I gave above should works except if the user want to stack the icons.

```html
<span class="icon is-large">
  <span class="fa-stack fa-lg">
    <i class="fa fa-camera fa-stack-1x"></i>
    <i class="fa fa-ban fa-stack-2x has-text-danger"></i>
  </span>
</span>
```

We will need a custom helper like `Icon.faStack` to let the users write is custom children here.

**Comment by alfonsogarciacaro** [comment]
I also had the same issue in my app. I think Bulma requires `fa-lg`, etc. because it now supports other icons beyond Font Awesome.  Apparently before, when only FA was supported, was not needed but I couldn't make it work by reverting the Bulma version to 0.5.2 or 0.5.1.

**Comment by MangelMaxime** [comment]
> I couldn't make it work by reverting the Bulma version to 0.5.2 or 0.5.1.

I tried too and failed too. That's really strange.

And yes it's probably due to the support of the new icon sets

**Comment by EdouardM** [comment]
Hello Maxime, 

I've implemented the Fa Size Option by following your guidance. 

It is working but I noticed that the options Icon.isSmall, Icon.isMedium, Icon.isLarge are completely ignored. I think they should be replaced by Fa Size 

I'll continue to work on this tonight. 

Bye, 
Edouard

**Comment by MangelMaxime** [comment]
What do you mean by ignored ? They are needed to set the size of the icon container (the span element)

**Comment by EdouardM** [comment]
You are right on the Icon size they should not be replaced.  
I continued to work on the issue now I have size and rotation of icons OK. I am on the stacked icon part. 

I'll keep you posted when this is done.
