### ISSUE TITLE
Should we provide Bulma version in doc?

### ISSUE THREAD

**Issue by kunjee17** [MangelMaxime/Fulma#55]
As our library, bulma is also growing. So, should we be providing 

Bulma version that we have covered and how much covered in docs?

It could be easier for people facing corner cases with Bulma and can pinned library to older version till library got updated.

**Comment by MangelMaxime** [comment]
@kunjee17 Yes that's a good idea.
I'm not sure how to displayed it. 

Perhaps, something like that:

| Fulma  |  Bulma | Font Awesome  | 
|---|---|---|
|  Current |  0.5.2  | 4.7.0  | 
|  0.1.0-beta-001 | 0.5.0  | 4.7.0  | 
|  0.1.0-alpha-001 | 0.4.7  | 4.7.0  | 

The idea being to create a new row when we upgrade one of the dependencies.

Or we can make a "version" page on the website, displaying the same info as in the README.md.

**Comment by alfonsogarciacaro** [comment]
At some point Paket we'll have to manage npm dependencies from Fable libraries too ;) @forki

**Comment by forki** [comment]
I know...
