### ISSUE TITLE
Navbar.isLight and others are missing

### ISSUE THREAD

**Issue by vasily-kirichenko** [MangelMaxime/Fulma#59]
I'd like to write
```fsharp
Navbar.navbar [ Navbar.isLight ]
```
instead of
```fsharp
Navbar.navbar [ Navbar.customClass "is-light" ]
```
Maybe I'm wrong and the latter code is idiomatic?

**Comment by MangelMaxime** [comment]
Oups...

I miss [this line](https://github.com/jgthms/bulma/blob/master/sass/components/navbar.sass#L40) when reading the `navbar` implementation of Bulma. And I probably have miss others too, I will need to recheck the components.

Thanks for pointed this error :)
