### ISSUE TITLE
Fulma animated Logo

### ISSUE THREAD

**Issue by evilz** [MangelMaxime/Fulma#66]
Hi all,

My co-worker is an awesome guy and just did this without I ask anything.
Take a look I think you will like this !

https://github.com/evilz/Fulma/blob/master/docs/public/assets/FULMA-LOGO-ANIM.mp4?raw=true

**Comment by kunjee17** [comment]
@evilz this is super awesome.... I loved it...

@MangelMaxime , @alfonsogarciacaro you should see this... it is too good...

**Comment by MangelMaxime** [comment]
@evilz Awesome 😍 

Did you know that the readme is missing a logo ? Telling that... Telling nothing...

**Comment by MangelMaxime** [comment]
And please thanks him for me :)

**Comment by evilz** [comment]
Thank Romain Noel =>http://noel-romain.over-blog.com/

**Comment by alfonsogarciacaro** [comment]
It's great, I love it!!! :clap: :clap: :clap:
