### ISSUE TITLE
Question re: [<RequireQualifiedAccess>] and code convention

### ISSUE THREAD

**Issue by NatElkins** [MangelMaxime/Fulma#67]
I was just reading through the README and I noticed this quote:

```
Fulma has been designed to provide the best experience over the Bulma CSS framework. To achieve this goal, we assume the user to follow some conventions.

Always open the "global" module and not the lower module of the hierarchie.
```
Is there any reason this isn't enforced with a `[<RequireQualifiedAccess>]` attribute?  This seems like it would let the compiler throw an error if that convention wasn't followed.

If there are no obvious problems with this I'm happy to submit a PR with the attribute on the relevant modules.

**Comment by MangelMaxime** [comment]
When writing Fulma, I though about using `[<RequireQualifiedAccess>]` and couldn't take a decision :).

I can't think of a reason why users would open the low level module. So perhaps, it's time to enforce the DSL with this attributes.

If you sent a PR I will accept it. You will need to do this in the three projects:

- Fulma
- Fulma.Extensions
- Fulma.Elmish
