### ISSUE TITLE
More helpers for commonly used props on wrapped elements?

### ISSUE THREAD

**Issue by johlrich** [MangelMaxime/Fulma#69]
I was specifically thinking of additional shortcuts similar to `Input.typeIsText` for commonly used props on other elements. Some examples would be things like: `Button.typeIsSubmit`, `Button.typeIsReset`, `Input.name ""`

Not a huge deal as users can add additional helpers in their app and the Button.props can always be used to set these types of things, but was wondering what your thoughts were on there being more helpers for additional commonly used non-Bulma props on elements out of box.

**Comment by MangelMaxime** [comment]
Yes, this is already on my todo list especially to make it easier to works with the forms.

However, as said in #70 I will not add `Button.typeIsSubmit` because a button can be a `div` or `a` element which don't accept this attribute.

**Comment by MangelMaxime** [comment]
Ok, so finally I found a way to add different helpers for the button modules.

Do you have others modules in mind ?

**Comment by johlrich** [comment]
Nothing else that I've ran into yet. I'll be deep into Fable/Elmish/Fulma the next few weeks and will either pile on here or another issue if more come up.
