### ISSUE TITLE
Rework the button element

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/Fulma#73]
Adding several elements support for the button result into an ugly code when using them with `yield` statement...

Solution: 

1. Support only one element
2. Duplicate the code, and use sub module to access the right types ?
3. Possible auto cast ? Perhaps usage of statically resolve type ?

Option 3, is my favorite will try it first.

**Comment by evilz** [comment]
### Issue with button_input 
#### All options must have the same type. 

Code:
```
Button.button_input [ Button.value "I am an input button"
                                                    Button.typeIsReset
                                                    Button.isPrimary ]
```

Error message : 
 ```
All elements of a list constructor expression must have the same type. 
This expression was expected to have type 'Button.Types.InputOnlyOption', but here has type 'Button.Types.Option'.
```

**Comment by MangelMaxime** [comment]
Ok, I think I have found a way to resolve this problem.

But this will need to rework the internal organization of Fulma. That's something which was already planned and that should be a good idea to do (easier to maintain and contribute) and also the code should be more F# centric on some part.

However, I need to evaluate the change this will lead to a latest breaking in the API (compiler will style have our back). But that's also mean after, that release of 1.0 should be close as the architecture will be finally fixed.

**Comment by MangelMaxime** [comment]
@evilz For the BulmaClasses I want to include the classes into the module directly like we did for the extensions: https://github.com/MangelMaxime/Fulma/blob/master/src/Fulma.Extensions/Calendar.fs#L9-L41

Should improve a little Fable compilation time or at least make it easier to locate the classes instead of a big giant file :p

**Comment by MangelMaxime** [comment]
Reminder for myself, use Enum instead of DU if this works. (need more test especially for inheritance)

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Regarding the helpers, although I agree it's better for the maintainer and the user to have a smaller API so it may be a good idea to remove them, it's also possible to include a cast in them to solve the problem of options with different type, like `let inline isSmall<'T> = Size IsSmall :> IButtonProperty`.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Hum, that's true but we will just hide the underline problem here. Also, by doing casting every helpers to `IButtonProperty` for example then we could use the `typeIsSubmit` helpers on a `button_a` which is wrong.

**Comment by evilz** [comment]
I still don't like empty interface like this :

```
type IAnchorOption =
            interface end

        type IBtnOption =
            interface end

        type IInputOption =
            interface end
```

I think it does not help developer to understand quickly and maybe neither the compilator.

What about DU in option list ?

**Comment by MangelMaxime** [comment]
What do you mean by ?

> What about DU in option list ?

End user don't need to know the internal architecture of a library. For example, I bet you don't now that you are using this construct every time you use `Fable.Helpers.React` in your project.

**Comment by evilz** [comment]
I was thinking of something like this :

```
type GenericOption =
            | Level of ILevelAndColor
            | Size of ISize
            | IsOutlined
            | IsInverted
            | IsLink
            | IsDisabled
            | State of IState
            | Props of IHTMLProp list
            | OnClick of (MouseEvent -> unit)
            | CustomClass of string
            
            
type AnchorOption =
            | Href of string
            | BtnOpt of GenericOption
            
            
let button_btn (options : GenericOption list) children = //...


let button_a (options : AnchorOption list) children = //....
```

But I'm not sure this so easy to use ...

**Comment by MangelMaxime** [comment]
So to use this you would write...

```fs
let view =
  Button.button_a [ Button.BtnOpt Button.IsOutline
                    Button.BtnOpt OnClick(fun _ -> ...) ]
    [ ]
```

**Comment by MangelMaxime** [comment]
Also, the benefit of using interface is that this should lead to a standard way to write "Fable-react DSL", because we are using the same structure for Fulma, Fable-react, react-leaflet, etc.

And this standard way will benefit of type checking thanks to F# compiler and sharing common properties like `CustomClass` and `Props` allowing everything wrapper to understand them by default.

The entry point of the bindings is the same for all they just have a difference in their pipeline output.

For me has a maintainer of several projects this is really important. I can jump from one repo or another really easily and especially when I provide the same experience to the end user.

I am working right now on testing my ideas and will create a PR when ready to ask feedback. Should be easier to discuss with the same code in front of us :)

**Comment by MangelMaxime** [comment]
I started the work on the next major version of Fulma, and as one of the focus for this next version is the user experience I think we should not have helpers like:

- `Button.button_btn`
- `Button.button_input`
- `Button.button_a`
- `Field.field_div`
- `Field.field_p`
- etc.

They look quite ugly, IMO. I need to test for the others components but for the button, if we apply the class `button` to any an anchor, button, input the display is the same. Also, because we are using Elmish we don't really care if the element is an anchor or button for example as in general we attach the event to the `OnClick` event.

Do you see a limitation to not have all the possible cases offered by Bulma wrapped into Fulma ? Personally, in all my application I have always used only one of the helpers.

I prefer to keep the API simpler and easier to read. And could add explanation about this decisions in the documentation with recommendation on how to use button element, to help in the transition :)

@evilz @alfonsogarciacaro @whitetigle

**Comment by whitetigle** [comment]
> for the button, if we apply the class button to any an anchor, button, input the display is the same
Then it's ok for me. Although I just used the `button_a`  in my project 😉

> I prefer to keep the API simpler and easier to read
👍

**Comment by alfonsogarciacaro** [comment]
Hmm, not sure. I've been using the helpers during last week, it's true that they didn't click immediately but I got used to them now :) I like that they tell you the elements wherein the Bulma `button` class is allowed. What would be the alternative? Could you please post some code? Would it be something like this?

```fsharp
Button.button
      [ a [ OnClick (fun _ -> dispatch MyMessage)
            Href Urls.myLink ]
          [ str "My link"] ]
```

In that case, how would Fulma work? By injecting the `button` class in the child element?

As a side node, when designing Fulma API one of the things to keep in mind is how easy is to convert Bulma HTML code to Fulma. Fulma documentation is awesome but sometimes we need to take code from other Bulma's samples. If the conversion could be done more or less automatically, we could create a web/plugin so users paste the code there and save most of the work. We still need to polish it but we've a prototype of a VS Code plugin to do this based on the Elm plugin, though it uses the React bindings directly instead.

**Comment by MangelMaxime** [comment]
Behavior would be the same as before. When you are using:

- `<a class="button"></a>`
- `<button class="button"></button>`

What do you tell yourself ? That you when an anchor which is styled as a button ?
No, personally I just want a button, what element is it behind don't matter in Fulma or Elmish world IMO. 

Code example, the simplest possible and more straightforward possible. 

```fs
Button.button [ OnClick (fun _ -> ())
                        Href Urls.myLink ]
    [ str "My link" ]
```

The only benefit of having support of `<input type="submit" class="button">` in the Bulma is to let the default behavior of the browser do the submit of the form for you ? But, really you don't want to do that in your application. Even in vanilla JS, we overload the submit behavior because browsers don't always send the data using the `Post` method and even if they don't support the `Delete` or `Put` HTTP Verb. Also, you want to validate the data before sending them so you don't let the default behavior doing it's job.

Bulma, Elmish allow us to not take in account the browsers behavior and conventions. We should take advantage of it to think as elements/components and not HTMLElement which are bad IMO.

Also, keep in mind that if in a very rare case user need to use an `<input type="submit" class="button">` they can still do it, using Fable.React DSL only. Fulma, don't prevent that.

**Comment by alfonsogarciacaro** [comment]
Ah, I see much better what you meant, thank you 😄 Ok, if the element behind the Bulma element is not important I agree it'll be much easier for the user if the helpers are removed :+1:

**Comment by MangelMaxime** [comment]
Some update, the "navbar" component use also a lot of "elements helpers" like `Navbar.item_a`, `Navbar.item_div`, etc.

Because, I am removing all the small helpers added to directly wrap the DUs describing the options available for the components, I am proposing this changes: 

```fs
// Old Api
Navbar.item_a [ Navbar.Item.hasDropdown
                Navbar.Item.isHoverable ]
              [ // Children here...
              ]

// New Api
Navbar.Item.a [ Navbar.Item.hasDropdown
                Navbar.Item.isHoverable ]
              [ // Children here...
              ]
```

Because, we are trying to all the helpers using an `_` I think it's a good way to expose the Api. What do you think ?

**Comment by alfonsogarciacaro** [comment]
You're right, as we're removing helpers with `_` for the cases where you do have to choose among different elements.  Just a couple of notes:

- I think autocompletion becomes unavailable after the third period, but here it shouldn't be a problem as there are only two and we have also other properties at the same level.
- It could be good to have the elements separated from other properties (`hasDropdown`, etc) so users don't have to find the different element options in a bigger list including other properties. Though I have some doubts about this, because with `Button.button` the `button` element also will appear in a list with other properties.

**Comment by MangelMaxime** [comment]
I believe auto-completion work inside `BulmaClasses.fs` so, I am not sure about this limit. And, if I remember correctly what I do, we should never go past the third period so that should be fine :). Also, having an API, like fulma going further than 3 period is bad design choice  IMO because UX and readability would not be good.

-----

About the second point, if we add an extra level to access the properties then we would reach the third period case :) and also, make the API more verbose. I am already making a lit bit more verbose with the re-design so we will see if we really to do the separation or no.

Also, in order to use Fulma I am expecting the user to have a minimal knowledge of Bulma otherwise we just end up writing code hopping this would work.

Your concern on the second point, is true for the root properties of an element or component. Example:

```fs
Button.button [ Button.Color IsSuccess ] [ str "My button" ]
```

But when we are in the "child"/"sub" level of an element or component then we indeed have a separation:

```fs
Navbar.Item.a [ Navbar.Item.HasDropdown
                Navbar.Item.IsHoverable ]
              [ // Children here...
              ]
```

If we add a separation level what should we write instead of `Button.Color` ? `Button.Props.Color` ?

And so should we write: `Navbar.Item.Props.IsHoverable` ?

Also, it's important to note that in the next API, the properties will always be "PascalCase" where "view functions" are in "camelCase".

This is becausese, I am removing all the little helpers which are adding a lot of maintenance cost and are really not worth it.

Once again I am not again all the changes people propose :) I just want to take time think about the API, because it's really the essence of Fulma and i underestimate it earlier. :)

**Comment by alfonsogarciacaro** [comment]
That makes a lot of sense, thanks a lot for the explanation. Actually, I was just thinking out loud and wasn't really very convinced very much myself about separating props and elements :) I totally agree we don't another separation level.

:tada: Happy New Year! :tada:

**Comment by MangelMaxime** [comment]
Happy new year to you too. 😊

For info, on fulma package I have to convert the Form module yet before making a first public PR. After that, discussing API etc. should be easier because we will all have the same code under our eyes.

**Comment by whitetigle** [comment]
Happy new year too! Let this be the Fablulmaish Year!

**Comment by evilz** [comment]
Happy new year !
