### ISSUE TITLE
Dotnet template

### ISSUE THREAD

**Issue by Nhowka** [MangelMaxime/Fulma#84]
The first time I used Fulma was by adding it to an existing Fable project. As I had no prior knowledge of Node.js or Webpack, I couldn't understand why nothing worked when I simply added Fulma to the client project and added Bulma to the package.json. After a long trial and error process, I imported the Bulma file to the project and told Webpack to use loaders for the sass file, then everything was in place.

It would be nice to have a simple template with everything Node related configured so everyone can use it out of the box without having to delete unneeded stuff from existing projects.

**Comment by MangelMaxime** [comment]
A template, has been created under the [SAFE-Stack](https://github.com/SAFE-Stack/SAFE-template), I will close this issue as the template should fix your problem :)

**Comment by Nhowka** [comment]
That template has [no loaders](https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/src/Client/webpack.config.js#L47-L68) for sass, also it loads the Bulma [from a CDN](https://github.com/SAFE-Stack/SAFE-template/blob/master/Content/src/Client/index.html#L5-L8) instead of bundling it. The problem is still there, having to reconfigure everything when using the extensions.

Not really a issue, but that template also has stuff for the server when sometimes just the client is needed.

**Comment by MangelMaxime** [comment]
I finally took the time to create the template. You can find the documentation [here](https://mangelmaxime.github.io/Fulma/#template)
