### ISSUE TITLE
Label in Switch is not centered vertically

### ISSUE THREAD

**Issue by vasily-kirichenko** [MangelMaxime/Fulma#88]
![image](https://user-images.githubusercontent.com/873919/34099503-bb6274dc-e3f0-11e7-84b6-37fdfdc76694.png)

**Comment by MangelMaxime** [comment]
Did you try to use the latest version of [bulma-switch](https://github.com/Wikiki/bulma-switch) ?

I find that on some components react is not resulting in the same result as pure html. It's the case for the checkbox, radio margin for example: https://github.com/MangelMaxime/Fulma/blob/master/docs/scss/main.scss#L129-L134

**Comment by vasily-kirichenko** [comment]
I started to use Switch just yesterday, so it's fresh :) 

Fixed with this

```sass
.switch[type="checkbox"] + label::before, label::after
    margin-top: 0.26em
```
![image](https://user-images.githubusercontent.com/873919/34101958-787890ea-e3f8-11e7-9bc3-6cb756d0f4af.png)

Thanks!

**Comment by MangelMaxime** [comment]
@vasily-kirichenko Thanks you for the fix, I will take a look at the issue later and if I have the same problem, I will probably add it to the documentation so people know how to fix it too :)
