### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by alfonsogarciacaro** [MangelMaxime/Fulma#92]
You know how much I love Fulma. It's great and I think it should be, together with Elmish, the standard tool to create Fable SPA apps. But it has a problem right now, it increases the size of the bundle a lot. Approximately, a _normal_ Fable SPA app is around 100KB minified but Fulma adds 200KB extra. It'd be great to reduce this as much as possible.

I want to keep working on PR #50 but you say you're going to do some refactoring so I'm not sure if it's better to wait a bit to avoid conflicts. In any case, I wanted to enumerate here the guidelines to get more optimized code so you can take them into account when restructuring the code

1. **Inline** small helpers
2. Use **LiteralAttribute** for string values
3. Use **enumerations** instead of DUs
4. Avoid **nested modules** as they prevent tree shaking

Point 1 is more or less finished. Point 2 requires a bit more work in BulmaClasses.fs and work for point 3 has been already started in #50. The last point will be the more complicated because Fulma contains many nested modules. Nested modules are ok if they only contain code that will be erased (inline functions, literal values or enumerations), but if they contain more complicated helpers it's better to put them in a separate file if it's not possible to put them in the root module. For example, instead of having a [nested module for Radio](https://github.com/MangelMaxime/Fulma/blob/0d031a8521779f7dea03da1639c8a349bca0c134/src/Fulma/Elements/Form.fs#L691), the code could be in the file `Fulma/Elements/Form/Radio.fs`.

I know this is a lot of work, so please tell me which parts do you want me to take care of and I'll help you tame the beast 💪

**Comment by MangelMaxime** [comment]
I am currently designing the next version of fulma which will remove the bulmaclasses.fs files and should also remove the nested modules which prevent the tree shaking. 

I hope to have a first version soon to ask advice from the community on it. As I also would like to remove support of different element for the same helper. From my experience then have the same result and make reading the code harder.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Is it dangerous to set the DU with an `[<Pojo>]` attributes ?

This erase the type completely from the generated bundle, and it's seems to work at runtime but I am not sure of myself.

Example:

```fs
    type GenericOption =
        | CustomClass of string
        | Props of IHTMLProp list

    type private GenericOptions =
        { CustomClass : string option
          Props : IHTMLProp list }

        static member Empty =
            { CustomClass = None
              Props = [] }
```

become:

```fs
    [<Pojo>]
    type GenericOption =
        | CustomClass of string
        | Props of IHTMLProp list

    type private GenericOptions =
        { CustomClass : string option
          Props : IHTMLProp list }

        static member Empty =
            { CustomClass = None
              Props = [] }
```

**Comment by alfonsogarciacaro** [comment]
This is funny. Yes, [you can use `Pojo` with DUs](http://fable.io/repl/#?code=open%20Fable.Core%0Aopen%20Fable.Core.JsInterop%0A%0A%5B%3CPojo%3E%5D%0Atype%20DU%20%3D%0A%20%20%7C%20Foo%20of%20money%3Afloat%0A%20%20%7C%20Bar%20of%20name%3Astring%20*%20age%3Aint%0A%20%20%0Alet%20x%20%3D%20Foo%205.%0Alet%20y%20%3D%20Bar(%22John%22%2C%2054)&astInput=false&babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2) but precisely today I was thinking how to use `Pojo` for Fulma so you don't have to use enums everywhere. I've opened an issue in Fable repo for discussion. Could you please check and give your opinion?

https://github.com/fable-compiler/Fable/issues/1308

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Because we closed https://github.com/fable-compiler/Fable/issues/1308, should I use the `[<Pojo>]` attribute ? 

Is there any edge case, if I use it ? Or should we make it optional via a compiler directive `#id FulmaOptimize ... #endif` ?

**Comment by MangelMaxime** [comment]
The question is more or less, does Fulma need the DUs types are runtime ? I would say no, so should be safe to remove the DUs from the runtime.

**Comment by alfonsogarciacaro** [comment]
Yes, if you won't be using it with `keyValueList` or similar you can try to use it. But it depends, Pojo DUs use strings instead of ints for the tag so that will take more code. When you have a version ready to test, I can have a look and see if `Pojo` could help in this case or not :+1:

**Comment by MangelMaxime** [comment]
Sure, will ping you in the PR. :)

**Comment by MangelMaxime** [comment]
We are waiting for Fable 2 to see how the size will be reduce.

**Comment by MangelMaxime** [comment]
I think we can close this one now. 

Not much more can be done on Fulma side IMO
