### ISSUE TITLE
Switch.props [ Id "xxx" ] does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [MangelMaxime/Fulma#95]
I have two Switches in a row on a Level and sometimes the first one renders as "on" however its `isChecked` property is `false` for sure. 

Trying to fix this problem I gave them a static `Id`:
```fsharp
yield
  Level.item []
    [ Switch.switch
        [ Switch.props [ Id "9bfa8d43-1b65-4e56-b0d3-ced77fde9bad" ]
          Switch.isRounded
          Switch.isOutlined
          Switch.isDanger
          Switch.isSmall
          Switch.isChecked logSettings.ErrorsOnly
          Switch.props [ OnClick (fun _ -> dispatch Msg.OnlyErrorsInLogSwitched) ]]
        [ str "errors only" ]]

yield
  Level.item []
    [ Switch.switch
        [ Switch.props [ Id "4d9f6448-2d0e-4883-8c6e-4eb8fd6550d8" ]
          Switch.isRounded
          Switch.isOutlined
          Switch.isInfo
          Switch.isSmall
          Switch.isChecked logSettings.AutoRefresh
          Switch.props [ OnClick (fun _ -> dispatch Msg.AutoRefreshLogSwitched) ]]
        [ str "auto refresh" ]]```
```
It's not helped and it seems the `Id`s are still random:

![_1](https://user-images.githubusercontent.com/873919/34864045-757d5e90-f783-11e7-890d-127448b7f86c.gif)

**Comment by alfonsogarciacaro** [comment]
Not sure if it's related, but the property used by React to uniquely identify a component in a list is `key` (this becomes a special property that's not accesible later, so IIRC the purpose of `id` is to make it also available to the programmer). Can you please try the following?

```fsharp
Switch.props [ Key "9bfa8d43-1b65-4e56-b0d3-ced77fde9bad" ]
```

**Comment by MangelMaxime** [comment]
You hit a react algorithm limitation. For example, when you want to render a list of item, 
react will tell you add a `Key` attributes to help him resolve similar elements.

It's also happen when you have similar elements closed like here in your case.

**Comment by vasily-kirichenko** [comment]
Thank you, guys, `Key` works :) However, the Switches "slide" into the right position immediately after rendering:

![_1](https://user-images.githubusercontent.com/873919/34866266-14afc38c-f78d-11e7-858f-94b1b27e563d.gif)

It's not a big problem, but looks a bit strange.

**Comment by MangelMaxime** [comment]
That's strange I don't see any CSS animation into the extension code...

I will close this issue as it's resolve and I am not sure we cant do something on Fulma side for the animation problem.

It's not happening on the [Docs](https://mangelmaxime.github.io/Fulma/#fulma-extensions/switch). Maybe it's a side effect of `Key` usage...
